name: Publish on crates.io
on:
  push:
    tags:
      - v?\d+.\d+.\d+
jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: crates.io

    steps:
      - uses: actions/checkout@v6
      - name: Publish on crates.io
        run: cargo publish