name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          release-type: 'rust'
          token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}

  binaries:
    needs: release
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        arch: [ x86_64, aarch64 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        if: ${{ needs.release.outputs.release_created == 'true' }}
      - name: Build artefacts
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            TARGET="${{ matrix.arch }}-unknown-linux-gnu"
            if [[ ${{ matrix.arch }} == "aarch64" ]]; then
              sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross
              export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
              export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            fi
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            TARGET="${{ matrix.arch }}-pc-windows-msvc"
          else
            TARGET="${{ matrix.arch }}-apple-darwin"
          fi
          echo TARGET=$TARGET
          rustup target add $TARGET
          cargo build --release --target $TARGET
          mkdir -p release/${TARGET}
          cp target/$TARGET/release/cidit release/${TARGET}/
          ls -la release
          tar -czf cidit-${{ github.ref_name }}-${TARGET}.tar.gz -C release/${TARGET} cidit
          ls -la
        if: ${{ needs.release.outputs.release_created == 'true' }}
      - name: Upload to release
        run: gh release upload "$GITHUB_REF_NAME" cidit-*.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ needs.release.outputs.release_created == 'true' }}

  crates:
    needs: release
    runs-on: ubuntu-latest
    environment: crates.io

    steps:
      - uses: actions/checkout@v6
        if: ${{ needs.release.outputs.release_created == 'true' }}
      - name: Publish on crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        if: ${{ needs.release.outputs.release_created == 'true' }}
